### ISSUE TITLE
Allow plain texts messages

### ISSUE THREAD

**Issue by Nizari** [cmdotcom/text-sdk-php#10]
Now we're forced to use type AUTO because now the code is as follows:

```php
**
 * Class MessageBody
 *
 * @package CMText
 */
class MessageBody implements JsonSerializable
{
    ...
    /**
     * @var string
     */
    private $type = MessageBodyTypes::AUTO;
    ...
```

There is no way to override this. Can you please create a setter so we can set the body type?

**Comment by joepb** [comment]
Hi @Nizari ,

The auto-feature is actually the de-facto standard way for us to accept messages.
It is indeed a supported gateway feature to force encoding to either GSM character set or UTF encoding, but as we consider that a legacy feature intended for exceptional situations, we haven't exposed it in the SDK because we often see it omitted or used wrongly.

What exactly is the reason you would *not* want message encoding to be detected automatically? We would like to know your use case, so we can make a good decision if we want to include this.

Thanks,

Joep

**Comment by Nizari** [comment]
He @joepb 

I was under the impression that with GSM characters you have 160 characters per message and with UTF encoding only 70 per message. In other words if we lock it on GSM we have more control over our message pricing (even if it would be at the cost of some message which would have a unicode character).

Or is that not the case anymore for CM?

**Comment by Nizari** [comment]
@joepb any updates on this?

**Comment by joepb** [comment]
Hey @Nizari,

Sorry, somehow this thread got burried in my github feeds. Found it now while cleaning up old issues.

Of course, within CM we love to make money, just like the next guy. But that's not the reason we chose AUTO as a default. 
Well a little, but not for these extra messages: the reason we decided to default this to AUTO is that analysis of our support tickets showed that many users were trying to send Unicode content but were unable to. This support pressure has pushed us to provide the automatic selection where-ever possible.

If you don't want to send Unicode content, you should make sure your content is (GSM 03.38)[https://en.wikipedia.org/wiki/GSM_03.38] compliant. For most customers quality is more important than price (within limits of course), and hav?ng qu?st??nmarks a?l ov?r the mes?age is not something most customers enjoy.

That said, we'd love to take PRs, as long as this addition makes the path of least resistance the AUTO selection. Adding optional alternatives is definitely welcome.

Joep
