### ISSUE TITLE
Laravel support

### ISSUE THREAD

**Issue by innoflash** [cmdotcom/text-sdk-php#15]
Can you make the package Laravel compatible or at least create a wrapper library for Laravel

**Comment by hexonthebeach** [comment]
I made a Service Provider for it on my own account
https://github.com/hexonthebeach/laravel-cmtext-provider
Any requests or issues in that package I am glad to fix or merge

**Comment by infostreams** [comment]
I just want to officially state here that I decided against using CM.com for my SMS needs because there's no official support for Laravel notification channels. I had already signed up for an account and had basically bit the bullet and chosen CM.com, but now I won't and will choose another provider.

Yes, I could write a notification channel myself because it's open source, but why would I? There's at least 15 other SMS providers that do offer one.

So, in case your project manager needs an argument why this is important: this is actively costing you customers. Thanks! The CM.com backend looks great, would have been nice to use it.
