### ISSUE TITLE
sender name is longer as allowed

### ISSUE THREAD

**Issue by tomboe311** [cmdotcom/text-sdk-php#18]
Sender name is larger then the allowed maximum length (16 digits for a phonenumber or 11 alphanumerical characters [a-zA-Z]). It is still tried to send the SMS. 

The SDK-Client returns "Accepted" as result, although the status is "Cancelled" in Messaging Log (cm.com).

Would be great to use fallback if sender name is to long or deny sending sms and returns correct status.

**Comment by hexonthebeach** [comment]
Thanks for the suggestion @tomboe311 
We need to make sure that this rule applies only to the SMS channel, it could be a nice addition indeed.

Currently it is not in since we try to keep the text-sdk's aligned through all the languages, and none have this check at the moment.
I will try to put a validator together but I will not promise anything in terms of a timeframe.

Please feel free to suggest a solid solution through a pr , or send me link to your wip if you have something.

**Comment by joepb** [comment]
Alpha length is an easy one, but validation of allowed characters is a more difficult one.

I think it's best to accept any input and let the business messaging gateway handle this correctly, as rules and insight might change over time and per locality. 
(For instance in South-Africa the use of longer sender IDs is perfectly fine, and has useful applications.) 

Perhaps it is advisable to make the normal limitations more clear in the SDK documentation. (Valid shortcode, MSISDN or max 11 characters alphanumeric)
